from exceptionError1 import ExceptionError1

class ExceptionInput(ExceptionError1):
    
    pass