from exceptionError2 import ExceptionError2

class Exception4(ExceptionError2):
    
    pass